<?php

namespace App\Services;

use App\Helpers\PhoneHelper;
use App\Models\Contact;
use App\Models\Team;
use App\Models\User;
use Illuminate\Support\Collection;

class UserResolverService
{
    /**
     * Ensure the WhatsApp writer (phone) is linked to a User (by phone) and, if that user is admin, to the team they are writing to.
     * Also links to a Contact in the given team when applicable (contact.user_id set).
     *
     * @param  string|null  $whatsappProfileName  Display name from WhatsApp (e.g. Baileys pushName); applied when user/contact still has auto-generated labels.
     */
    public function linkPhoneToContactInTeam(int $teamId, string $phone, ?string $whatsappProfileName = null): void
    {
        $cleanNumber = preg_replace('/[^0-9]/', '', $phone);
        if ($cleanNumber === '')
        {
            return;
        }

        $displayName = $this->sanitizeWhatsAppProfileName($whatsappProfileName);
        $staffUser = $this->findTeamStaffUserByPhone($teamId, $cleanNumber)
            ?? $this->findKnownStaffUserByPhoneDigits($teamId, $cleanNumber);

        if ($staffUser !== null)
        {
            $this->ensureTeamMembershipRole($staffUser, $teamId);
        }

        $contact = $this->findContactInTeamByPhone($teamId, $cleanNumber);

        if ($contact !== null)
        {
            $updates = [];

            if ($staffUser !== null)
            {
                if ($this->shouldAssignStaffUserToContact($contact, $staffUser, $teamId))
                {
                    $updates['user_id'] = $staffUser->id;
                }
            } elseif ($contact->user_id)
            {
                $linkedUser = User::withoutGlobalScopes()->find($contact->user_id);
                if ($linkedUser !== null && $this->isPlaceholderWhatsAppUser($linkedUser))
                {
                    $updates['user_id'] = null;
                }
            }

            if ($displayName !== null && $this->isAutoGeneratedWhatsAppContactLabel($contact->name))
            {
                $updates['name'] = $displayName;
            }

            if ($updates !== [])
            {
                $contact->update($updates);
            }

            return;
        }

        try
        {
            $team = Team::query()->find($teamId);
            $creatorId = $team?->user_id;

            Contact::withoutGlobalScopes()->create([
                'team_id' => $teamId,
                'user_id' => $staffUser?->id,
                'creator_id' => $creatorId,
                'name' => $displayName ?? ('Contacto '.$cleanNumber),
                'phone' => $cleanNumber,
                'status_id' => 1,
            ]);
        } catch (\Throwable $e)
        {
            report($e);
        }
    }

    /**
     * Team staff or global admin whose {@see User::$phone} matches the inbound WhatsApp number.
     */
    public function resolveTeamStaffByPhone(int $teamId, string $phone): ?User
    {
        $cleanNumber = preg_replace('/[^0-9]/', '', $phone);
        if ($cleanNumber === '')
        {
            return null;
        }

        return $this->findTeamStaffUserByPhone($teamId, $cleanNumber)
            ?? $this->findKnownStaffUserByPhoneDigits($teamId, $cleanNumber)
            ?? $this->findStaffUserBySamePhoneLine($teamId, $cleanNumber);
    }

    /**
     * First name we can greet on WhatsApp. Placeholder labels like
     * "Usuario 34722372858" / "Contacto 34722372858" are treated as unknown.
     */
    public function greetingNameForWhatsAppPhone(int $teamId, string $phone): ?string
    {
        $contact = $this->findContactInTeamByPhone($teamId, $phone);
        if ($contact !== null)
        {
            $contactName = $this->usableGreetingName((string) ($contact->name ?? ''));
            if ($contactName !== null)
            {
                return $contactName;
            }

            if ($contact->user_id)
            {
                $linkedUser = User::withoutGlobalScopes()->find($contact->user_id);
                $userName = $this->usableGreetingName((string) ($linkedUser?->name ?? ''));
                if ($userName !== null)
                {
                    return $userName;
                }
            }
        }

        return null;
    }

    public function findContactInTeamByPhone(int $teamId, string $phone): ?Contact
    {
        return $this->findContactsInTeamByPhone($teamId, $phone)->first();
    }

    /**
     * @return Collection<int, Contact>
     */
    public function findContactsInTeamByPhone(int $teamId, string $phone): Collection
    {
        $cleanNumber = preg_replace('/[^0-9]/', '', $phone);
        if ($cleanNumber === '')
        {
            return collect();
        }

        $phoneNormalizedSql = "REPLACE(REPLACE(REPLACE(CONCAT(phone, ''), ' ', ''), '+', ''), '-', '')";

        return Contact::withoutGlobalScopes()
            ->where('team_id', $teamId)
            ->where(function ($query) use ($cleanNumber, $phoneNormalizedSql)
            {
                $query->whereHas('sources', function ($q) use ($cleanNumber)
                {
                    $q->where('source_id', 2)->where('value', $cleanNumber);
                })
                    ->orWhereRaw("{$phoneNormalizedSql} = ?", [$cleanNumber]);

                if (strlen($cleanNumber) >= 11 && str_starts_with($cleanNumber, '34'))
                {
                    $query->orWhereRaw("{$phoneNormalizedSql} = ?", [substr($cleanNumber, -9)]);
                }
                if (strlen($cleanNumber) === 9)
                {
                    $query->orWhereRaw("{$phoneNormalizedSql} = ?", ['34'.$cleanNumber]);
                }
            })
            ->orderBy('id')
            ->get();
    }

    /**
     * Resolve a real User for agent context (team staff or contact-linked account). Never creates placeholder users.
     *
     * @param  string|null  $phone  Phone number (e.g. WhatsApp, can include prefix)
     * @param  int|null  $contactId  Optional contact ID to resolve via contact.user_id
     * @return User|null Staff or linked portal user, or null for CRM-only WhatsApp contacts
     */
    public function resolveUserForConversation(?string $phone = null, ?int $contactId = null, ?int $teamId = null): ?User
    {
        $user = null;

        if ($phone !== null && $phone !== '')
        {
            if ($teamId !== null)
            {
                $user = $this->findTeamStaffUserByPhone($teamId, $phone);
            }

            if ($user === null)
            {
                $user = $this->findUserByPhone($phone);
            }

            if ($user !== null && $teamId !== null && $this->isPlaceholderWhatsAppUser($user))
            {
                $cleanNumber = preg_replace('/[^0-9]/', '', $phone);
                if ($cleanNumber !== '')
                {
                    $contact = $this->findContactInTeamByPhone($teamId, $cleanNumber)
                        ?? $this->findContactByNormalizedPhone($cleanNumber);
                    if ($contact?->user_id)
                    {
                        $linkedUser = User::withoutGlobalScopes()->find($contact->user_id);
                        if ($linkedUser !== null && $this->userIsTeamStaff($linkedUser, $teamId))
                        {
                            $user = $linkedUser;
                        }
                    }
                }
            }

            if ($user !== null && $this->isPlaceholderWhatsAppUser($user))
            {
                $user = null;
            }
        }

        if ($user === null && $contactId !== null)
        {
            $user = $this->findUserByContactId($contactId);
            if ($user !== null && $this->isPlaceholderWhatsAppUser($user))
            {
                $user = null;
            }
        }

        return $user;
    }

    /**
     * Find user by phone: direct User.phone or via Contact (WhatsApp source value or contacts.phone).
     */
    /**
     * Prefer a team staff account (admin/editor/collaborator pivot or global admin) when the phone matches.
     * Avoids treating an internal user as a placeholder WhatsApp client.
     */
    protected function findTeamStaffUserByPhone(int $teamId, string $phoneNumber): ?User
    {
        $cleanNumber = preg_replace('/[^0-9]/', '', $phoneNumber);
        if ($cleanNumber === '')
        {
            return null;
        }

        $phoneVariants = $this->phoneVariantsForDigits($cleanNumber);

        $candidates = User::withoutGlobalScopes()
            ->where(function ($query) use ($phoneVariants)
            {
                foreach ($phoneVariants as $variant)
                {
                    $query->orWhere('phone', $variant);
                }
            })
            ->whereHas('teams', function ($query) use ($teamId)
            {
                $query->where('teams.id', $teamId)
                    ->whereIn('team_user.role', ['admin', 'editor', 'collaborator']);
            })
            ->get();

        if ($candidates->isEmpty())
        {
            return $this->findTeamStaffUserByContactPhone($teamId, $phoneVariants);
        }

        $globalAdmin = $candidates->first(fn (User $user) => $user->hasAnyRole(['admin', 'root']));
        if ($globalAdmin !== null)
        {
            return $globalAdmin;
        }

        $pivotAdmin = $candidates->first(function (User $user) use ($teamId)
        {
            $role = $user->teams()->where('teams.id', $teamId)->value('team_user.role');

            return in_array((string) $role, ['admin', 'editor'], true);
        });

        return $pivotAdmin ?? $candidates->first();
    }

    protected function findUserByPhone(string $phoneNumber): ?User
    {
        $cleanNumber = preg_replace('/[^0-9]/', '', $phoneNumber);
        if ($cleanNumber === '')
        {
            return null;
        }

        $user = User::withoutGlobalScopes()->where('phone', $cleanNumber)->first();
        if ($user)
        {
            return $user;
        }

        // Only try without-country-code for Spanish numbers (34 + 9 digits) to avoid false matches
        // e.g. 49486831349987 last-9 would wrongly match Spanish 34831349987
        if (strlen($cleanNumber) === 11 && str_starts_with($cleanNumber, '34'))
        {
            $withoutCountryCode = substr($cleanNumber, -9);
            $user = User::withoutGlobalScopes()->where('phone', $withoutCountryCode)->first();
            if ($user)
            {
                return $user;
            }
        }

        $contact = $this->findContactByNormalizedPhone($cleanNumber);
        if ($contact === null)
        {
            return null;
        }

        return $this->userFromContact($contact);
    }

    /**
     * Resolve contact by WhatsApp source or normalized contacts.phone (digits only, optional national suffix match).
     */
    protected function findContactByNormalizedPhone(string $cleanNumber): ?Contact
    {
        $phoneNormalizedSql = "REPLACE(REPLACE(REPLACE(CONCAT(phone, ''), ' ', ''), '+', ''), '-', '')";

        return Contact::withoutGlobalScopes()
            ->where(function ($query) use ($cleanNumber, $phoneNormalizedSql)
            {
                $query->whereHas('sources', function ($q) use ($cleanNumber)
                {
                    $q->where('source_id', 2)->where('value', $cleanNumber);
                })
                    ->orWhereRaw("{$phoneNormalizedSql} = ?", [$cleanNumber]);

                if (strlen($cleanNumber) > 9)
                {
                    $national = substr($cleanNumber, -9);
                    $query->orWhereRaw("{$phoneNormalizedSql} = ?", [$national]);
                }
            })
            ->first();
    }

    protected function userFromContact(Contact $contact): ?User
    {
        if (! $contact->user_id)
        {
            return null;
        }

        return User::withoutGlobalScopes()->find($contact->user_id);
    }

    /**
     * Find user by contact ID (contact.user_id).
     */
    protected function findUserByContactId(int $contactId): ?User
    {
        $contact = Contact::withoutGlobalScopes()->with('user')->find($contactId);

        return $contact?->user;
    }

    private function sanitizeWhatsAppProfileName(?string $raw): ?string
    {
        if ($raw === null)
        {
            return null;
        }

        $trimmed = trim($raw);
        if ($trimmed === '')
        {
            return null;
        }

        $stripped = preg_replace('/[\x00-\x1F\x7F]/u', '', strip_tags($trimmed));
        if ($stripped === null || $stripped === '')
        {
            return null;
        }

        return mb_substr($stripped, 0, 255);
    }

    private function usableGreetingName(string $name): ?string
    {
        $name = trim($name);
        if ($name === '' || $this->isGeneratedWhatsAppDisplayName($name))
        {
            return null;
        }

        return $name;
    }

    public function isGeneratedWhatsAppDisplayName(string $name): bool
    {
        return $this->isAutoGeneratedWhatsAppUserLabel($name)
            || $this->isAutoGeneratedWhatsAppContactLabel($name);
    }

    private function isAutoGeneratedWhatsAppUserLabel(string $name): bool
    {
        return (bool) preg_match('/^Usuario\s+[0-9]+$/u', trim($name));
    }

    private function isAutoGeneratedWhatsAppContactLabel(string $name): bool
    {
        return (bool) preg_match('/^Contacto\s+[0-9]+$/u', trim($name));
    }

    private function shouldAssignStaffUserToContact(Contact $contact, User $staffUser, int $teamId): bool
    {
        if (empty($contact->user_id))
        {
            return true;
        }

        $linkedUser = User::withoutGlobalScopes()->find($contact->user_id);
        if ($linkedUser === null)
        {
            return true;
        }

        if ($linkedUser->id === $staffUser->id)
        {
            return false;
        }

        return $this->isPlaceholderWhatsAppUser($linkedUser)
            || $this->shouldPreferExistingContactUser($linkedUser, $staffUser, $teamId);
    }

    private function shouldPreferExistingContactUser(User $linkedUser, User $resolvedUser, int $teamId): bool
    {
        if ($linkedUser->id === $resolvedUser->id)
        {
            return false;
        }

        $linkedIsStaff = $this->userIsTeamStaff($linkedUser, $teamId);
        $resolvedIsPlaceholder = $this->isPlaceholderWhatsAppUser($resolvedUser);

        return $linkedIsStaff || ($resolvedIsPlaceholder && ! $this->userIsTeamStaff($resolvedUser, $teamId));
    }

    private function userIsTeamStaff(User $user, int $teamId): bool
    {
        return app(AssistantToolAuthorizationService::class)->hasFullAssistantToolAccess($user, $teamId);
    }

    private function isPlaceholderWhatsAppUser(User $user): bool
    {
        return str_ends_with(strtolower((string) $user->email), '@chat.placeholder');
    }

    /**
     * @param  list<string>  $phoneVariants
     */
    private function findTeamStaffUserByContactPhone(int $teamId, array $phoneVariants): ?User
    {
        if ($teamId < 1 || $phoneVariants === [])
        {
            return null;
        }

        $phoneNormalizedSql = "REPLACE(REPLACE(REPLACE(CONCAT(phone, ''), ' ', ''), '+', ''), '-', '')";

        $contacts = Contact::withoutGlobalScopes()
            ->where('team_id', $teamId)
            ->where(function ($query) use ($phoneVariants, $phoneNormalizedSql)
            {
                foreach ($phoneVariants as $variant)
                {
                    $query->orWhereRaw("{$phoneNormalizedSql} = ?", [$variant])
                        ->orWhereHas('sources', function ($sourceQuery) use ($variant)
                        {
                            $sourceQuery->where('source_id', 2)->where('value', $variant);
                        });
                }
            })
            ->get();

        foreach ($contacts as $contact)
        {
            if ($contact->user_id)
            {
                $linkedUser = User::withoutGlobalScopes()->find($contact->user_id);
                if ($linkedUser !== null && $this->userIsTeamStaff($linkedUser, $teamId))
                {
                    return $linkedUser;
                }
            }

            $email = strtolower(trim((string) ($contact->email ?? '')));
            if ($email === '' || ! filter_var($email, FILTER_VALIDATE_EMAIL) || str_ends_with($email, '@chat.placeholder'))
            {
                continue;
            }

            $staffByEmail = User::withoutGlobalScopes()
                ->whereRaw('LOWER(email) = ?', [$email])
                ->whereHas('teams', function ($query) use ($teamId)
                {
                    $query->where('teams.id', $teamId)
                        ->whereIn('team_user.role', ['admin', 'editor', 'collaborator']);
                })
                ->first();

            if ($staffByEmail !== null)
            {
                return $staffByEmail;
            }
        }

        return null;
    }

    /**
     * @return list<string>
     */
    private function findStaffUserBySamePhoneLine(int $teamId, string $cleanNumber): ?User
    {
        $candidates = User::withoutGlobalScopes()
            ->whereNotNull('phone')
            ->where(function ($query) use ($teamId)
            {
                $query->whereHas('teams', function ($teamQuery) use ($teamId)
                {
                    $teamQuery->where('teams.id', $teamId);
                })
                    ->orWhereHas('roles', function ($roleQuery)
                    {
                        $roleQuery->where('name', 'root');
                    });
            })
            ->get();

        foreach ($candidates as $candidate)
        {
            if (! PhoneHelper::digitsBelongToSameLine((string) $candidate->phone, $cleanNumber))
            {
                continue;
            }

            if ($this->shouldTreatUserAsInboundTeamStaff($candidate, $teamId))
            {
                return $candidate;
            }
        }

        return null;
    }

    private function findKnownStaffUserByPhoneDigits(int $teamId, string $cleanNumber): ?User
    {
        foreach ($this->phoneVariantsForDigits($cleanNumber) as $variant)
        {
            $candidate = User::withoutGlobalScopes()->where('phone', $variant)->first();
            if ($candidate === null)
            {
                continue;
            }

            if ($this->shouldTreatUserAsInboundTeamStaff($candidate, $teamId))
            {
                return $candidate;
            }
        }

        return null;
    }

    /**
     * @return list<string>
     */
    private function phoneVariantsForDigits(string $cleanNumber): array
    {
        $variants = [$cleanNumber];
        if (strlen($cleanNumber) === 11 && str_starts_with($cleanNumber, '34'))
        {
            $variants[] = substr($cleanNumber, -9);
        }

        return $variants;
    }

    private function ensureTeamMembershipRole(User $user, int $teamId): void
    {
        $membership = $user->teams()->where('team_id', $teamId)->first();

        if ($membership === null)
        {
            if (! $this->isPlatformRootUser($user))
            {
                return;
            }

            $user->teams()->attach($teamId, ['role' => 'admin']);

            return;
        }

        $desiredRole = $this->resolveTeamPivotRoleForUser($user, $teamId);
        $currentRole = (string) ($membership->pivot->role ?? '');
        if ($currentRole === 'client' && $desiredRole !== 'client')
        {
            $user->teams()->updateExistingPivot($teamId, ['role' => $desiredRole]);
        }
    }

    private function resolveTeamPivotRoleForUser(User $user, int $teamId): string
    {
        if ($this->isPlatformRootUser($user))
        {
            return 'admin';
        }

        $existingRole = $user->teams()
            ->where('teams.id', $teamId)
            ->value('team_user.role');

        if (is_string($existingRole) && in_array($existingRole, ['admin', 'editor', 'collaborator'], true))
        {
            return $existingRole;
        }

        if ($user->hasRole('admin') && $existingRole === 'client')
        {
            return 'admin';
        }

        return 'client';
    }

    private function isPlatformRootUser(User $user): bool
    {
        return $user->hasRole('root');
    }

    private function userHasStaffPivotOnTeam(User $user, int $teamId): bool
    {
        $role = $user->teams()->where('teams.id', $teamId)->value('team_user.role');

        return is_string($role) && in_array($role, ['admin', 'editor', 'collaborator'], true);
    }

    private function shouldTreatUserAsInboundTeamStaff(User $user, int $teamId): bool
    {
        if ($this->isPlatformRootUser($user) || $this->userHasStaffPivotOnTeam($user, $teamId))
        {
            return true;
        }

        return $user->hasRole('admin') && $user->teams()->where('team_id', $teamId)->exists();
    }
}
