---
deployment:
    tasks:
        - export DEPLOYPATH=/home/revcms8
        - /bin/cp -R * $DEPLOYPATH
        - rm -rf /home/revcms8/public_html
        - ln -s /home/revcms8/public /home/revcms8/public_html
        - cd $DEPLOYPATH
        - /bin/scl enable ea-php82 '/opt/cpanel/composer/bin/composer install --no-interaction'
        - /bin/scl enable ea-php82 'php artisan clear-compiled'
        - /bin/scl enable ea-php82 'php artisan migrate'
        - /bin/scl enable ea-php82 'php artisan db:seed'
