---
deployment:
  tasks:
    - export DEPLOYPATH=/home/revcms8
    - rm -rf /home/revcms8/database
    - /bin/cp -R * $DEPLOYPATH
    - rm -rf /home/revcms8/public_html
    - ln -s /home/revcms8/public /home/revcms8/public_html
    - cd $DEPLOYPATH
    - /bin/scl enable ea-php82 '/opt/cpanel/composer/bin/composer update --no-interaction'
    - /bin/scl enable ea-php82 'php artisan migrate:fresh --seed'
