<?php

// Variables
return [
    'creatorName' => 'Humano',
    'creatorUrl' => 'https://www.linkedin.com/in/diego-mascarenhas/',
    'templateName' => env('APP_NAME', 'HUMANO'),
    // "templateSuffix" => "v0.9",
    'templateVersion' => '2.0.1',
    'templateFree' => false,
    'templateDescription' => 'Sistema de gestión de relaciones con clientes (CRM) completo y profesional. Gestiona contactos, proyectos, facturación y comunicaciones en una sola plataforma.',
    'templateKeyword' => 'crm, gestión de clientes, contactos, proyectos, facturación, laravel, dashboard',
    'ogImage' => 'images/system-onboarding/whatsapp-image.jpg',
    'ogImageWidth' => 552,
    'ogImageHeight' => 552,
    'ogImageAlt' => 'Humano — gestiona tu negocio desde cualquier lugar',
    'licenseUrl' => 'https://www.gnu.org/licenses/agpl-3.0.html',
    'livePreview' => 'https://humano.revisionalpha.es/',
    'productPage' => 'https://revisionalpha.es',
    'support' => 'https://api.whatsapp.com/send/?phone=34722372858&text=I+need+technical+support+por&type=phone_number&app_absent=0',
    'moreThemes' => 'https://github.com/diego-mascarenhas',
    'documentation' => 'https://github.com/diego-mascarenhas/humano',
    'generator' => '',
    'changelog' => 'https://github.com/diego-mascarenhas/humano/activity',
    'repository' => 'https://github.com/diego-mascarenhas/humano',
    'gitRepo' => 'diego-mascarenhas',
    'gitRepoAccess' => 'humano',
    'githubFreeUrl' => 'https://github.com/diego-mascarenhas/humano',
    'facebookUrl' => '',
    'twitterUrl' => 'https://x.com/devcraftsman',
    'githubUrl' => 'https://github.com/diego-mascarenhas',
    'dribbbleUrl' => '',
    'instagramUrl' => '',
    'logo' => [
        'path' => env('APP_LOGO_PATH', 'assets/logo.png'),
        'path_dark' => env('APP_LOGO_PATH_DARK', 'assets/logo-dark.svg'),
        'path_light' => env('APP_LOGO_PATH_LIGHT', 'assets/logo-light.svg'),
        'path_iso' => env('APP_LOGO_PATH_ISO', 'assets/logo-iso.svg'),
        'path_iso_dark' => env('APP_LOGO_PATH_ISO_DARK', 'assets/logo-iso-dark.svg'),
        'path_iso_light' => env('APP_LOGO_PATH_ISO_LIGHT', 'assets/logo-iso-light.svg'),
        'fallback' => env('APP_LOGO_FALLBACK', 'assets/logo.svg'),
        'iso_fallback' => env('APP_LOGO_ISO_FALLBACK', 'assets/logo-iso.svg'),
    ],
];
