name: Create artifact for distribution

on:
  push:
    branches:
      - dev

jobs:
  create-deloyment-artifacts:
    name: Create deployment artifacts
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Compile CSS and JavaScript
      run: |
        npm install
        npm run build


    - name: Configure PHP 8.2
      uses: shivammathur/setup-php@master
      with:
        php-version: '8.2'
        extensions: mbstring, ctype, fileinfo, openssl, PDO, bcmath, json, tokenizer, xml

    - name: Install Composer Dependencies
      run: composer install --no-dev --no-interaction --prefer-dist

    - name: Create deployment artifact
      env:
        GITHUB_SHA: ${{ github.sha }}

      run: tar -czf "${{ github.sha }}".tar.gz --exclude=*.git --exclude=node_modules *

    - name: Create artifact for distribution
      uses: actions/upload-artifact@v2
      with:
        name: app-build
        path: ${{ github.sha }}

    # - name: Export deployment matrix
    #   id: export-deployment-matrix
    #   run: |


      