name: Staging revision alpha (ES) Deployment 10

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - name: Generate key
      run: php artisan key:generate
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
    
    - name: Deploy to Server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST_STAGING_REVISIONALPHA_ES }}
        username: ${{ secrets.SSH_USERNAME_STAGING_REVISIONALPHA_ES }}
        password: ${{ secrets.SSH_PASSWORD_STAGING_REVISIONALPHA_ES }}
        port: ${{ secrets.SSH_PORT_STAGING_REVISIONALPHA_ES }}
        script: |
          rsync -avz --delete ./ ${{ secrets.SSH_USERNAME_STAGING_REVISIONALPHA_ES }}@${{ secrets.SSH_HOST_STAGING_REVISIONALPHA_ES }}:/home/revstag/public_html
          ssh ${{ secrets.SSH_USERNAME_STAGING_REVISIONALPHA_ES }}@${{ secrets.SSH_HOST_STAGING_REVISIONALPHA_ES }} "cd /home/revstag/public_html && composer install --no-interaction --prefer-dist --optimize-autoloader && php artisan migrate --force && php artisan config:cache && php artisan route:cache && php artisan view:cache"
